# Generated by Django 3.2.2 on 2021-05-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0006_auto_20210510_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=600),
        ),
    ]
