# Generated by Django 3.2.2 on 2021-05-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
